name: budget
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  image_picker: ^1.0.4
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.1
  syncfusion_flutter_charts: ^23.2.4
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.1
  firebase_messaging: ^14.7.5
  flutter_local_notifications: ^16.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
